theme: jekyll-theme-cayman

repository: strzaleczka/strzaleczka.github.io

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

exclude: 
- docker
- uml

title: Strzaleczka's stuff
email: pio.strzalka@gmail.com

tag_page: '/blog/tags/'

# Google Analytics
google_analytics: G-M0X69XTSWF

