theme: jekyll-theme-cayman

repository: strzaleczka/strzaleczka.github.io

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

exclude: docker

title: Go create!
email: pio.strzalka@gmail.com

tag_page: '/blog/tags/'

