@startuml

[app_fdrive] #GreenYellow
[app_pas_encoder]
[mc_interface]
[mcpwn_foc]
[commands]
[terminal]
[conf_general]
[ch]

[chevents]

app_fdrive -right-> app_pas_encoder
app_fdrive --> mc_interface
app_fdrive --> mcpwn_foc
app_fdrive --> commands
app_fdrive --> terminal
app_fdrive --> conf_general
app_fdrive --> ch
app_fdrive --> chevents



@enduml