@startuml

skinparam backgroundColor #FEFFFF

skinparam InterfaceBackgroundColor #DEF2F1
skinparam InterfaceBorderColor #3AAFA9

skinparam component {
  StartColor Black
  EndColor Black
  BackgroundColor #3AAFA9
  FontName Yu Gothic UI Semibold
  ArrowColor #17252A
  ArrowThickness 2
  ArrowFontName Yu Gothic UI Semibold
}

    package removable1 as "Removable battery" {
        [battery]
    }

    package embedded as "Embedded on bike frame" {
        package crank {
            [pas]
        }
        
        package handlebar {
            [on_off_switch]
            [potentiometer]
        }
        package battery_mount {
            [soft_start]
            interface plug_in_connector_female
        }
        potentiometer --> plug_in_connector_female : 3 wires
        pas --> plug_in_connector_female : 4 wires
        on_off_switch --> plug_in_connector_female : 3 wires
        ' connection_board --> plug_in_connector_female :  5 wires
    }
    
    package removable as "Removable mount" {
        interface plug_in_connector_male
        [vesc]
        [motor]
        [nrf]
        [capacitor_board]
        plug_in_connector_male -> capacitor_board : power             
        plug_in_connector_male -> vesc : signal
        capacitor_board --> vesc : power
        vesc --> motor
        vesc --> nrf
    } 
    
    battery -left-> soft_start : 2 wires
    soft_start --> plug_in_connector_female : 2 wires
    plug_in_connector_female -left-> plug_in_connector_male : 7 wires
@enduml
