@startuml
[*] --> Drive_NotArmed
Drive_NotArmed: Entry / Release Motor
Drive_NotArmed --> Drive_Armed : PAS Signal TurnBack / overall_errors = 0U
Drive_Armed --> Drive_NotArmed : PAS Signal TurnBack
  
state Drive_Armed {
    [*] --> Armed_Idle
    Armed_Idle --> Armed_Triggered : PAS Moving Forward
    state Armed_Triggered {
        [*] --> Jump
        Jump --> CoolDown : motorAttached == FALSE
        CoolDown --> Jump : TimeElapsed
        Jump --> Armed_Running : motorAttached == TRUE
        Armed_Running --> Jump : motorAttached == FALSE

        Jump --> Attaching_Error : motorAttached == FALSE && attempts_left == 0U

        Attaching_Error : Entry / overall_errors ++
        Jump : Entry / Set Motor Speed = SPEED_GOAL
        CoolDown :  Entry / Release Motor, Set Timer = 500ms

    }

    Armed_Triggered : Entry / attempts_left = 3
    
    
    Armed_Triggered --> Armed_Idle: !PAS Moving Forward
}

Attaching_Error --> Drive_NotArmed : overall_errors > 3U / Store error in memory

@enduml